# Используем официальный образ Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install --production

# Копируем остальные файлы в контейнер
COPY . /app

# Указываем команду для запуска приложения
EXPOSE ${PORT:-3000}

CMD ["npm", "start"]
