services:
  backend:
    restart: unless-stopped
    env_file: backend/.env.backend
    build:
      context: backend
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/tmp:/app/tmp

  frontend:
    restart: unless-stopped
    env_file: frontend/.env.frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend/users_whitelist.json:/app/users_whitelist.json