services:
  database:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_agent
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    restart: unless-stopped
    env_file: backend/.env.backend
    build:
      context: backend
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - database

  frontend:
    restart: unless-stopped
    env_file: frontend/.env.frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend/users_whitelist.json:/app/users_whitelist.json

volumes:
  pgdata: